title: RL SSL BOT
description: F
template:
  repo: rl-ssl-bot-template
  name: rl-ssl-bot
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
